name: RKY9
on: [push]
jobs:
  Build_RPM_Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Docker build container
        run: docker build -t qemu_full_build .
      - name: Build
        run: docker run --name qemu_full_build qemu_full_build
      - name: Getting ready for delivery
        run: mkdir ../artifacts;docker ps -a; docker cp qemu_full_build:/rhel-qemu-builder/qemu-7.1.0/build/qemu-system-x86_64 ../artifacts/; cd ../artifacts; ls; pwd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: qemu_full
          path: /home/runner/work/rhel-qemu-builder/artifacts
          if-no-files-found: warn